### ISSUE TITLE
Bug: Race condition if using Async calls

### ISSUE THREAD

**Issue by glynn1211** [aws-powertools/powertools-lambda-dotnet#310]
### Expected Behaviour

When running many tasks asynchronously that emit a metric they all run successfully

### Current Behaviour

Currently it is possible for the async code to hit a race condition that returns a System.ArgumentException: An item with the same key has already been added.

### Code snippet

```csharp
private static readonly object Lock = new();

    [Fact]
    public async Task WhenClearAllDimensions_NoDimensionsInOutput()
    {
        // Arrange
        var methodName = Guid.NewGuid().ToString();
        var consoleOut = new StringWriter();
        Console.SetOut(consoleOut);

        var configurations = new Mock<IPowertoolsConfigurations>();

        var metrics = new Metrics(configurations.Object,
            nameSpace: "dotnet-powertools-test",
            service: "testService");

        var handler = new MetricsAspectHandler(metrics,
            false);

        var eventArgs = new AspectEventArgs { Name = methodName };


        // Act
        handler.OnEntry(eventArgs);
        Metrics.ClearDefaultDimensions();
        var tasks = new List<Task>();
        for (var i = 0; i < 100; i++)
        {
            tasks.Add(MetricTask());
        }

        await Task.WhenAll(tasks);


        handler.OnExit(eventArgs);

        var metricsOutput = consoleOut.ToString();

        // Assert
        Assert.Contains("{\"Namespace\":\"dotnet-powertools-test\",\"Metrics\":[{\"Name\":\"Metric Name\",\"Unit\":\"Count\"}],\"Dimensions\":[[]]",
            metricsOutput);

        // Reset
        handler.ResetForTest();
    }

    private Task MetricTask()
    {
        return Task.Run(() =>
        {
            Metrics.ClearDefaultDimensions();
            Metrics.SetNamespace("nameSpace");
            Metrics.AddMetric($"Metric Name", 1, MetricUnit.Count);
        });
    }
```

### Steps to Reproduce

Code snippet above contains a test that when ran returns a System.ArgumentException: An item with the same key has already been added.

### Powertools for AWS Lambda (.NET) version

latest

### AWS Lambda function runtime

dotnet6

### Debugging logs

```csharp
System.ArgumentException
An item with the same key has already been added. Key: Metric Name
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at AWS.Lambda.Powertools.Metrics.RootNode.get_MetricData() in C:\Users\*\aws-lambda-powertools-dotnet\libraries\src\AWS.Lambda.Powertools.Metrics\Model\RootNode.cs:line 52
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.GetMemberAndWriteJsonExtensionData(Object obj, WriteStack& state, Utf8JsonWriter writer)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryWrite(Utf8JsonWriter writer, T value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.TryWrite(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.WriteCore(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.JsonSerializer.WriteUsingSerializer[TValue](Utf8JsonWriter writer, TValue& value, JsonTypeInfo jsonTypeInfo)
   at System.Text.Json.JsonSerializer.WriteStringUsingSerializer[TValue](TValue& value, JsonTypeInfo jsonTypeInfo)
   at System.Text.Json.JsonSerializer.Serialize[TValue](TValue value, JsonSerializerOptions options)
   at AWS.Lambda.Powertools.Metrics.RootNode.Serialize() in C:\Users\*\aws-lambda-powertools-dotnet\libraries\src\AWS.Lambda.Powertools.Metrics\Model\RootNode.cs:line 68
   at AWS.Lambda.Powertools.Metrics.MetricsContext.Serialize() in C:\Users\*\aws-lambda-powertools-dotnet\libraries\src\AWS.Lambda.Powertools.Metrics\Model\MetricsContext.cs:line 163
   at AWS.Lambda.Powertools.Metrics.Metrics.AWS.Lambda.Powertools.Metrics.IMetrics.Flush(Boolean metricsOverflow) in C:\Users\*\aws-lambda-powertools-dotnet\libraries\src\AWS.Lambda.Powertools.Metrics\Metrics.cs:line 200
   at AWS.Lambda.Powertools.Metrics.MetricsAspectHandler.OnExit(AspectEventArgs eventArgs) in C:\Users\*\aws-lambda-powertools-dotnet\libraries\src\AWS.Lambda.Powertools.Metrics\Internal\MetricsAspectHandler.cs:line 70
   at AWS.Lambda.Powertools.Metrics.Tests.DuplicateKeyTest.WhenClearAllDimensions_NoDimensionsInOutput() in C:\Users\*\aws-lambda-powertools-dotnet\libraries\tests\AWS.Lambda.Powertools.Metrics.Tests\DuplicateKeyTest.cs:line 48
   at Xunit.Sdk.TestInvoker`1.<>c__DisplayClass48_0.<<InvokeTestMethodAsync>b__1>d.MoveNext() in /_/src/xunit.execution/Sdk/Frameworks/Runners/TestInvoker.cs:line 264
--- End of stack trace from previous location ---
   at Xunit.Sdk.ExecutionTimer.AggregateAsync(Func`1 asyncAction) in /_/src/xunit.execution/Sdk/Frameworks/ExecutionTimer.cs:line 48
   at Xunit.Sdk.ExceptionAggregator.RunAsync(Func`1 code) in /_/src/xunit.core/Sdk/ExceptionAggregator.cs:line 90
```

**Comment by hjgraca** [comment]
@glynn1211 pull request created. Thank you for raising this issue
